syntax = "proto3";

package exclave.core.proxy.snell;
option csharp_namespace = "Exclave.Core.Proxy.Snell";
option go_package = "github.com/exclavenetwork/exclave-core/v5/proxy/snell";
option java_package = "com.github.exclavenetwork.exclave.core.proxy.snell";
option java_multiple_files = true;

import "common/protoext/extensions.proto";
import "common/net/address.proto";

message ClientConfig {
  option (exclave.core.common.protoext.message_opt).type = "outbound";
  option (exclave.core.common.protoext.message_opt).short_name = "snell";

  exclave.core.common.net.IPOrDomain address = 1;
  uint32 port = 2;
  string psk = 3;
  uint32 version = 4;
  string user_key = 5;
  bool reuse = 6;
  string obfs_mode = 7;
  string obfs_host = 8;
  string mode = 9;
  DomainStrategy domain_strategy = 10;
  string obfs_uri = 11;

  enum DomainStrategy {
    USE_IP = 0;
    USE_IP4 = 1;
    USE_IP6 = 2;
    PREFER_IP4 = 3;
    PREFER_IP6 = 4;
  }
}
